export default {
    ADD_TODO: "ADD_TODO",
    UPDATE_TODO: "UPDATE_TODO",
    REMOVE_TODO: "REMOVE_TODO",
    CLEAR_REDUX_STATE: "CLEAR_REDUX_STATE",
    CHECK_CHANGE: "CHECK_CHANGE",
    FILTER_LIST: "FILTER_LIST"
}